
// Default number of file generators
#define DEFAULT_GENERATORS 5
#define DEFAULT_MIN_TIME 1
#define DEFAULT_MAX_TIME 10


#define DEFAULT_MIN_ROWS 10000
#define DEFAULT_MAX_ROWS 10000
#define DEFAULT_MIN_COLS 10
#define DEFAULT_MAX_COLS 10
#define DEFAULT_MIN_VALUE 0.0
#define DEFAULT_MAX_VALUE 100.0
#define DEFAULT_MISS_PERCENTAGE 10
